language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - RUST_VERSION=nightly
sudo: required
dist: trusty
install:
  - python -c "import sysconfig; print('\n'.join(map(repr,sorted(sysconfig.get_config_vars().items()))))"
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=$RUST_VERSION
  - export PATH="$HOME/rust/bin:$PATH"
script:
  - python setup.py develop
